package com.example.testpsicologici.service;

import org.springframework.stereotype.Component;

import java.util.Map;

import static java.util.Map.entry;

@Component
public class ReferenceContributionCatalogue {

    private static final String DEFAULT_CONTRIBUTION =
            "Fonte consultata per definire i temi esplorati e mantenere un linguaggio informativo e prudente.";

    private static final Map<String, String> CONTRIBUTIONS = Map.ofEntries(
            entry("https://www.cdc.gov/autism/hcp/diagnosis/index.html",
                    "Riferimento per comunicazione e interazione sociale, comportamenti ripetitivi, interessi, sensibilità sensoriale e necessità di considerare la storia dello sviluppo."),
            entry("https://www.nice.org.uk/guidance/cg142/chapter/Recommendations",
                    "Riferimento per la valutazione complessiva nell'adulto, il funzionamento nei diversi contesti, la storia dello sviluppo e le possibili spiegazioni alternative."),
            entry("https://www.iss.it/documents/20126/8968214/Linea_Guida_ASD_adulti.pdf/b15434a0-3bcd-60c0-46b2-e5b34dc170bd?t=1691389267884",
                    "Linea guida ISS/SNLG per inquadrare valutazione, diagnosi e supporto dell'autismo nell'adulto nel contesto sanitario italiano; non valida il questionario dell'app."),
            entry("https://www.nice.org.uk/guidance/ng87/chapter/recommendations",
                    "Riferimento per disattenzione, iperattività e impulsività, esordio nell'infanzia, impatto in più contesti e necessità di una valutazione specialistica."),
            entry("https://www.nhs.uk/conditions/adhd-adults/",
                    "Riferimento informativo per attenzione, gestione del tempo, organizzazione, irrequietezza, impazienza e impulsività nell'adulto."),
            entry("https://pubmed.ncbi.nlm.nih.gov/39942433/",
                    "Studio di validazione italiana di un'intervista clinica per l'ADHD adulto, utile per il contesto nazionale e per la necessità di una valutazione strutturata; non riguarda il questionario dell'app."),
            entry("https://www.nhs.uk/mental-health/conditions/obsessive-compulsive-disorder-ocd/symptoms/",
                    "Riferimento per distinguere pensieri ossessivi e compulsioni, descrivere il loro ciclo e considerare disagio e interferenza nella vita quotidiana."),
            entry("https://www.nimh.nih.gov/health/publications/obsessive-compulsive-disorder-when-unwanted-thoughts-or-repetitive-behaviors-take-over",
                    "Riferimento per pensieri indesiderati, rituali ripetitivi, tempo occupato e impatto sul funzionamento, senza equiparare singole esperienze a una diagnosi."),
            entry("https://pubmed.ncbi.nlm.nih.gov/18701254/",
                    "Validazione italiana dell'OCI/OCI-R su campioni comunitario e clinico, consultata per multidimensionalità e possibili effetti del livello di istruzione; punteggi e proprietà non sono trasferibili all'app."),
            entry("https://socy.umd.edu/about-us/rosenberg-self-esteem-scale",
                    "Riferimento per il costrutto di autostima globale e per la distinzione tra valutazioni positive e negative di sé."),
            entry("https://doi.org/10.1177/0963721414547414",
                    "Riferimento per considerare l'autostima relativamente stabile ma modificabile nel corso della vita."),
            entry("https://pubmed.ncbi.nlm.nih.gov/25580614/",
                    "Studio sulla struttura della Rosenberg Self-Esteem Scale e sulla sua invarianza in campioni europei, incluso un campione italiano; non fornisce norme per il questionario dell'app."),
            entry("https://www.salute.gov.it/new/sites/default/files/imported/C_17_pubblicazioni_3313_allegato.pdf",
                    "Documento del Consiglio Superiore di Sanità consultato per il quadro delle dipendenze comportamentali e della cosiddetta love addiction."),
            entry("https://pmc.ncbi.nlm.nih.gov/articles/PMC12284683/",
                    "Riferimento per il rapporto tra attaccamento insicuro, ansia di separazione e comportamenti relazionali problematici, tenendo conto dell'eterogeneità del costrutto."),
            entry("https://pubmed.ncbi.nlm.nih.gov/42029817/",
                    "Revisione sistematica con meta-analisi consultata per distinguere dipendenza emotiva, love addiction e amore maniacale e per evitare di trattarli come un unico costrutto diagnostico."),
            entry("https://doi.org/10.1016/S0005-7894(73)80120-0",
                    "Riferimento storico per la misurazione comportamentale e situazionale dell'assertività."),
            entry("https://doi.org/10.1016/S0191-8869(98)00252-9",
                    "Riferimento per la struttura multidimensionale dell'assertività: espressione, limiti, iniziativa e comportamenti assertivi positivi."),
            entry("https://pubmed.ncbi.nlm.nih.gov/21721362/",
                    "Validazione interculturale della SIB in un ampio campione studentesco italiano, utile per multidimensionalità e differenze culturali; i risultati non sono norme universali."),
            entry("https://doi.org/10.1177/1754073916639667",
                    "Riferimento per le aree di percezione, facilitazione del pensiero, comprensione e gestione delle emozioni."),
            entry("https://doi.org/10.1037/0003-066X.63.6.503",
                    "Riferimento per distinguere il modello di abilità dalle concezioni più ampie dell'intelligenza emotiva basate su tratti e competenze."),
            entry("https://pubmed.ncbi.nlm.nih.gov/23536991/",
                    "Validazione italiana del MSCEIT v2.0 consultata per struttura e distinzione da intelligenza e personalità; il MSCEIT è una prova di abilità diversa dall'autovalutazione dell'app."),
            entry("https://doi.org/10.1007/BF01172967",
                    "Riferimento per preoccupazione per gli errori, standard personali, dubbi sulle azioni, aspettative percepite e organizzazione."),
            entry("https://pubmed.ncbi.nlm.nih.gov/2027080/",
                    "Riferimento per distinguere perfezionismo orientato verso di sé, verso gli altri e socialmente prescritto."),
            entry("https://pubmed.ncbi.nlm.nih.gov/33835908/",
                    "Confronto psicometrico di forme brevi della HFMPS in campioni italiani, consultato anche perché i risultati misti invitano a non assumere una struttura o soglie universali."),
            entry("https://www.nimh.nih.gov/health/publications/social-anxiety-disorder-more-than-just-shyness",
                    "Riferimento per paura di essere osservati o giudicati, manifestazioni nelle interazioni e nelle prestazioni, evitamento e impatto sul funzionamento."),
            entry("https://www.nice.org.uk/guidance/cg159/ifp/chapter/assessment-and-diagnosis-for-adults",
                    "Riferimento per preoccupazioni sociali, paura dell'imbarazzo o dell'attenzione, evitamento e interferenza nella vita quotidiana."),
            entry("https://www.clinicalneuropsychiatry.org/download/assessing-social-anxiety-disorder-psychometric-properties-of-the-italian-social-phobia-inventory-i-spin/",
                    "Studio peer-reviewed sulla versione italiana dello SPIN, consultato per pertinenza linguistica e culturale; non autorizza a trasferire cut-off o proprietà al questionario dell'app."),
            entry("https://www.merckmanuals.com/professional/psychiatric-disorders/personality-disorders/narcissistic-personality-disorder-npd",
                    "Riferimento per il carattere pervasivo del disturbo, grandiosità, bisogno di ammirazione, empatia e necessità di una valutazione basata su criteri clinici."),
            entry("https://pubmed.ncbi.nlm.nih.gov/37702183/",
                    "Meta-analisi sul legame debole, a livello di gruppo, tra narcisismo e violenza di coppia; non permette di diagnosticare il partner né di spiegare il singolo comportamento abusante."),
            entry("https://www.istat.it/wp-content/uploads/2025/11/La-violenza-contro-le-donne-dentro-e-fuori-la-famiglia_Anno-2025.pdf",
                    "Dati istituzionali italiani su isolamento, controllo, svalorizzazione, minacce e violenza economica nella coppia, usati per descrivere comportamenti senza attribuire diagnosi."),
            entry("https://www.nimh.nih.gov/health/publications/generalized-anxiety-disorder-gad",
                    "Riferimento per distinguere ansia occasionale e preoccupazione persistente e difficile da controllare, insieme ai sintomi fisici e cognitivi associati."),
            entry("https://www.nice.org.uk/guidance/cg113/chapter/Appendix-Assessing-generalised-anxiety-disorder",
                    "Riferimento per preoccupazione in più ambiti, difficoltà di controllo, durata, sintomi associati e funzionamento quotidiano."),
            entry("https://pubmed.ncbi.nlm.nih.gov/37149049/",
                    "Studio italiano su struttura e invarianza del GAD-7; il campione cardiologico e prevalentemente maschile limita la generalizzazione e non fornisce soglie per l'app."),
            entry("https://www.who.int/news-room/fact-sheets/detail/depression",
                    "Riferimento per umore depresso o perdita di interesse, durata, sintomi cognitivi e fisici, funzionamento, trattabilità e sicurezza."),
            entry("https://www.nimh.nih.gov/health/publications/depression",
                    "Riferimento per eterogeneità dei sintomi, piacere, energia, colpa, concentrazione, sonno, appetito, funzionamento e possibili cause alternative."),
            entry("https://www.iss.it/documents/20126/0/Consensus_1_2022_IT.pdf",
                    "Documento ISS sul contesto italiano delle terapie psicologiche per ansia e depressione; supporta l'orientamento ai servizi, non la validità o lo scoring del questionario."),
            entry("https://pubmed.ncbi.nlm.nih.gov/39932691/",
                    "Studio italiano sulla struttura e invarianza del PHQ-9 in persone con cardiopatia; il campione clinico specifico non consente di trasferire norme o cut-off alla popolazione generale."),
            entry("https://pubmed.ncbi.nlm.nih.gov/9686454/",
                    "Riferimento per distinguere la disposizione positiva alla cura dalla focalizzazione sugli altri associata a dipendenza valutativa e trascuratezza di sé."),
            entry("https://pubmed.ncbi.nlm.nih.gov/15647153/",
                    "Riferimento teorico per la cura degli altri a esclusione del sé e per il possibile legame con il disagio psicologico, senza considerare problematica la cura in quanto tale."),
            entry("https://pubmed.ncbi.nlm.nih.gov/30518269/",
                    "Revisione sul self-silencing consultata per il ruolo di genere, relazioni e cultura; non esiste una solida validazione italiana del people pleasing come costrutto unitario."),
            entry("https://doi.org/10.1037/h0086006",
                    "Lavoro originario sul fenomeno dell'impostore, la difficoltà a interiorizzare i successi e l'attribuzione dei risultati a cause esterne."),
            entry("https://pmc.ncbi.nlm.nih.gov/articles/PMC6463809/",
                    "Revisione delle definizioni e delle proprietà psicometriche delle principali misure, utile per mantenere distinta questa esperienza da una condizione diagnosticabile."),
            entry("https://doi.org/10.1007/s12144-025-07865-1",
                    "Studio europeo d'invarianza dell'Impostor-Profile 30, con versione italiana; le deviazioni del campione italiano mostrano perché norme e interpretazioni non vanno trasferite automaticamente."),
            entry("https://pubmed.ncbi.nlm.nih.gov/3043527/",
                    "Riferimento per distinguere condotte deliberatamente autodistruttive, compromessi con costi prevedibili e strategie controproducenti, mantenendo una lettura non moralistica."),
            entry("https://pubmed.ncbi.nlm.nih.gov/17201571/",
                    "Meta-analisi di riferimento per procrastinazione, autoregolazione, avversione al compito, impulsività, tempi e divario tra intenzione e azione."),
            entry("https://pubmed.ncbi.nlm.nih.gov/27630595/",
                    "Confronto psicometrico di due misure di procrastinazione in sei Paesi europei, inclusa l'Italia; riguarda la procrastinazione e non valida un costrutto unitario di autosabotaggio."),
            entry("https://pubmed.ncbi.nlm.nih.gov/28604275/",
                    "Validazione multicentrica italiana del BPDSI-IV consultata per eterogeneità e domini affettivi, comportamentali, impulsivi e relazionali; strumento, campioni clinici e punteggi sono diversi da quelli dell'app."),
            entry("https://iris.who.int/bitstream/handle/10665/375767/9789240077263-eng.pdf?sequence=1",
                    "Descrizioni cliniche ICD-11 consultate per il funzionamento complessivo di personalità e il pattern borderline; non definiscono la struttura o le soglie del questionario informativo."),
            entry("https://www.salute.gov.it/new/sites/default/files/imported/C_17_pubblicazioni_2461_allegato.pdf",
                    "Documento italiano sui percorsi di cura consultato per valutazione clinica, funzionamento e condizioni concomitanti nei disturbi gravi di personalità; non riguarda l'autovalutazione online."),
            entry("https://www.iss.it/-/diagnosi-trattamento-disturbo-borderline-personalit%C3%A0_in-prog",
                    "Pagina ISS che documenta lo sviluppo di una linea guida italiana su diagnosi e trattamento; il lavoro non è ancora concluso e non sostiene raccomandazioni definitive."),
            entry("https://pubmed.ncbi.nlm.nih.gov/36407970/",
                    "Validazione italiana dell'AAS-R consultata per la dimensione di ansia dell'attaccamento e i timori di rifiuto e abbandono; lo strumento, il campione giovane e i punteggi non sono trasferibili all'app."),
            entry("https://pmc.ncbi.nlm.nih.gov/articles/PMC7453162/",
                    "Validazione italiana dell'ECR-12 consultata per distinguere ansia ed evitamento e per le associazioni con ruminazione e difficoltà interpersonali; riguarda uno strumento diverso."),
            entry("https://pubmed.ncbi.nlm.nih.gov/33937113/",
                    "Studio italiano consultato per distinguere l'ansia di separazione da ansia generale e dimensioni borderline; il campione di studenti giovani e il disegno correlazionale limitano la generalizzazione."),
            entry("https://doi.org/10.1023/A:1024515519160",
                    "Revisione teorica consultata per attenzione alla disponibilità, ricerca di prossimità e regolazione affettiva nell'attaccamento; non dimostra cause individuali né valida item o soglie."),
            entry("https://pubmed.ncbi.nlm.nih.gov/31704432/",
                    "Validazione italiana della FoMOs consultata per i nuclei di preoccupazione e desiderio di connessione; popolazioni giovani, struttura, item e punteggi non sono trasferibili al questionario dell'app."),
            entry("https://doi.org/10.1016/j.chbr.2024.100374",
                    "Validazione italiana dell'ON-FoMO consultata per distinguere appartenenza, riconoscimento, reazioni alla disconnessione e conseguenze dell'uso online; riguarda giovani adulti e un altro strumento."),
            entry("https://doi.org/10.1016/j.chb.2013.02.014",
                    "Lavoro fondativo consultato per la definizione della FOMO come preoccupazione per esperienze non condivise e desiderio di connessione; associazioni e misura originale non validano l'app."),
            entry("https://doi.org/10.1371/journal.pone.0308643",
                    "Scoping review preregistrata consultata per eterogeneità di definizioni, dimensionalità, stato-tratto e confini online e offline; non fornisce una struttura definitiva né inferenze causali."),
            entry("https://pz.harvard.edu/sites/default/files/Theory%20of%20MI.pdf",
                    "Sintesi ufficiale di Project Zero consultata per delimitare i domini linguistico e intrapersonale nella teoria delle intelligenze multiple; presenta la teoria e non valida item, aree o scoring dell'app."),
            entry("https://doi.org/10.1016/j.intell.2006.02.004",
                    "Studio su prove ispirate a otto domini consultato per le correlazioni con il fattore generale e il modesto supporto specifico; campione canadese e operazionalizzazione non validano i questionari dell'app."),
            entry("https://www.coe.int/en/web/common-european-framework-reference-languages/mediation",
                    "Quadro del Consiglio d'Europa consultato per distinguere ricezione, produzione, interazione e mediazione e considerare il plurilinguismo; non misura l'intelligenza di Gardner."),
            entry("https://www.inapp.gov.it/piaac/conosci-piaac/lindagine-piaac",
                    "Fonte istituzionale italiana consultata per distinguere prove cognitive di literacy e questionario sugli usi quotidiani; livelli e risultati PIAAC non sono trasferibili al test dell'app."),
            entry("https://doi.org/10.14605/CS1532206",
                    "Primo studio italiano della Self-Reflection and Insight Scale consultato per distinguere autoriflessione e insight; il campione di 112 studenti toscani e la misura differente non validano l'app."),
            entry("https://pubmed.ncbi.nlm.nih.gov/26379571/",
                    "Studio italiano consultato per distinguere consapevolezza interocettiva autoriferita e accuratezza a un compito; il campione studentesco prevalentemente femminile non è rappresentativo."),
            entry("https://doi.org/10.1027/1016-9040/a000124",
                    "Revisione critica consultata per definire la resilienza attraverso difficoltà significativa e adattamento e per trattarla come processo dinamico; non valida item, aree o soglie dell'app."),
            entry("https://pubmed.ncbi.nlm.nih.gov/25317257/",
                    "Sintesi interdisciplinare consultata per distinguere tratto, processo ed esito e includere fattori biologici, psicologici, sociali e culturali; non fornisce una misura universale."),
            entry("https://pubmed.ncbi.nlm.nih.gov/27031088/",
                    "Validazione italiana della Resilience Scale for Adults consultata per rappresentare risorse individuali, familiari e sociali; campioni e strumento differenti non validano il questionario dell'app."),
            entry("https://pubmed.ncbi.nlm.nih.gov/34850301/",
                    "Validazione italiana della RS-14 su volontari adulti consultata per l'eterogeneità della struttura; fattori, proprietà e punteggi dello strumento non sono trasferiti all'app."),
            entry("https://pubmed.ncbi.nlm.nih.gov/21294858/",
                    "Revisione metodologica consultata per differenze tra le scale di resilienza, qualità psicometriche variabili e assenza di un unico standard; non autorizza soglie normative nell'app."),
            entry("https://doi.org/10.3389/fpsyg.2022.1013584",
                    "Validazione italiana della MJS breve consultata per le componenti cognitiva, emotiva e comportamentale e l'invarianza per genere; campione, item e punteggi non validano il questionario dell'app."),
            entry("https://doi.org/10.1177/026540758900600203",
                    "Studio originario della Multidimensional Jealousy Scale consultato per la distinzione tra pensieri, emozioni e comportamenti; gli item non sono stati copiati né adattati."),
            entry("https://doi.org/10.4067/S0718-48082017000200203",
                    "Revisione sistematica consultata per la natura multideterminata e culturalmente contestuale della gelosia romantica; prevalenza di studi ex post facto e campioni universitari limita le conclusioni."),
            entry("https://doi.org/10.3390/ijerph17165682",
                    "Revisione mixed-methods consultata per distinguere infedeltà reale, sospetta e accusata e per l'associazione con violenza di coppia; non consente causalità o previsione individuale."),
            entry("https://www.who.int/publications/i/item/WHO-RHR-12.36",
                    "Fonte WHO consultata per distinguere isolamento, monitoraggio degli spostamenti e restrizioni come comportamenti di controllo; non è una misura di gelosia né classifica il singolo caso."),
            entry("https://www.pariopportunita.gov.it/it/numeri-utili/1522-numero-antiviolenza-e-antistalking/",
                    "Pagina ufficiale consultata per indicare correttamente il servizio pubblico gratuito 1522 per aiuto e consiglio su violenza e stalking, distinguendolo dal 112 per le emergenze."),
            entry("https://flore.unifi.it/handle/2158/656647",
                    "Validazione italiana della SWLS su 676 lavoratori adulti consultata per la struttura unidimensionale; campione, item, scala e punteggi non validano il questionario originale dell'app."),
            entry("https://www.istat.it/comunicato-stampa/soddisfazione-dei-cittadini-anno-2024/",
                    "Fonte statistica ufficiale italiana consultata per distinguere soddisfazione complessiva e ambiti specifici; scala 0–10, soglie e stime di popolazione non sono trasferite all'app."),
            entry("https://pubmed.ncbi.nlm.nih.gov/16367493/",
                    "Studio fondativo della SWLS consultato per definire la soddisfazione globale come valutazione cognitiva distinta da affetti e solitudine; nessun item è stato copiato o adattato."),
            entry("https://www.oecd.org/en/publications/oecd-guidelines-on-measuring-subjective-well-being-2025-update_9203632a-en/full-report/measuring-subjective-well-being_b4b53f27.html",
                    "Linee guida OECD consultate per distinguere life evaluation, affetti, eudaimonia e benessere oggettivo; il formato di frequenza e le quattro aree dell'app restano scelte originali non validate."),
            entry("https://pubmed.ncbi.nlm.nih.gov/28324322/",
                    "Revisione di 27 studi d'invarianza della SWLS consultata per la cautela nei confronti tra culture ed età; non fornisce norme o interpretazioni per il questionario dell'app."),
            entry("https://doi.org/10.1371/journal.pone.0313107",
                    "Studio multicentrico della SWLS in 65 nazioni e 40 lingue consultato per i limiti di trasferibilità culturale; non valida item, aree, soglie o confronti individuali nell'app."),
            entry("https://doi.org/10.3390/ijerph19095282",
                    "Validazione italiana della PCL-5 su 601 adulti consultata per finestra dell'ultimo mese e complessità fattoriale; item, punteggi e migliore adattamento del modello a sette fattori non validano le quattro aree originali dell'app."),
            entry("https://pubmed.ncbi.nlm.nih.gov/25266475/",
                    "Indagine probabilistica sulla popolazione adulta italiana consultata per il contesto di esposizione e PTSD; stime epidemiologiche di gruppo e criteri dello studio non spiegano il singolo caso."),
            entry("https://www.ptsd.va.gov/professional/treat/essentials/dsm5_ptsd.asp",
                    "Sintesi istituzionale consultata per esposizione, quattro famiglie di esperienze, durata, interferenza ed esclusioni; non sostituisce una valutazione clinica e non valida il questionario."),
            entry("https://www.who.int/news-room/fact-sheets/detail/post-traumatic-stress-disorder",
                    "Fonte WHO consultata per varietà delle reazioni dopo eventi potenzialmente traumatici, esperienze principali, interferenza e disponibilità di trattamenti; dati globali non sono stime individuali."),
            entry("https://www.nice.org.uk/guidance/ng116/chapter/Recommendations",
                    "Linea guida consultata per riconoscimento, valutazione, dissociazione, condizioni complesse, sicurezza e trattamento; il contesto britannico e le raccomandazioni cliniche non validano l'autovalutazione originale."),
            entry("https://www.who.int/publications-detail-redirect/9789241505406",
                    "Linea guida WHO consultata per distinguere stress acuto, PTSD e lutto e delimitare la gestione clinica; non fornisce soglie, pesi o interpretazioni per l'app."),
            entry("https://pubmed.ncbi.nlm.nih.gov/1920064/",
                    "Studio fondativo consultato per i quattro prototipi adulto-romantici e la combinazione dei modelli di sé e degli altri; campioni storici e metodo diverso non validano item o algoritmo dell'app."),
            entry("https://pubmed.ncbi.nlm.nih.gov/25074302/",
                    "Validazione ECR-R su 1.363 adulti italiani consultata per la struttura bifattoriale ansia/evitamento; i 36 item, la scala a sette categorie e i punteggi non vengono trasferiti."),
            entry("https://pubmed.ncbi.nlm.nih.gov/25559192/",
                    "Analisi taxometrica consultata perché favorisce una rappresentazione dimensionale rispetto a categorie naturali degli orientamenti generali e specifici; non definisce soglie o distanze per l'app."),
            entry("https://pmc.ncbi.nlm.nih.gov/articles/PMC4845754/",
                    "Revisione consultata per ansia, evitamento e strategie di iperattivazione o disattivazione sotto stress relazionale; associazioni di gruppo non spiegano il singolo caso."),
            entry("https://pmc.ncbi.nlm.nih.gov/articles/PMC5820166/",
                    "Studi longitudinali consultati per variazioni entro la persona e rispetto a una relazione specifica; non producono previsioni o classificazioni per l'utente italiano."),
            entry("https://doi.org/10.1177/00332941251394980",
                    "Sviluppo dell'LQ-11 consultato per la definizione emergente, il bisogno intenso di attaccamento e la trascuratezza di sé e altri; campioni autoselezionati, item, fattori e punteggi non sono trasferiti all'app."),
            entry("https://doi.org/10.1007/s11896-024-09674-x",
                    "Rapid scoping review consultata per lo stato limitato della letteratura e per distinguere focalizzazione interna da condotte persistenti e indesiderate; non consente di prevedere stalking o violenza nel singolo caso."),
            entry("https://doi.org/10.46743/2160-3715/2015.1420",
                    "Studio fenomenologico consultato per ruminazione, idealizzazione e perdita di centralità del sé; i sei partecipanti internazionali non forniscono fattori, frequenze o generalizzazioni."),
            entry("https://doi.org/10.1111/spc3.12629",
                    "Revisione integrativa consultata per distinguere teoria della limerenza e più ampia passione romantica e per le evidenze miste sul ruolo causale dell'incertezza."),
            entry("https://doi.org/10.3390/ijerph20136197",
                    "Revisione sistematica mixed-methods di 95 studi consultata per multidimensionalità, contesto, sostegno e risultati eterogenei della parentificazione; non valida aree o soglie dell'app."),
            entry("https://doi.org/10.1007/s10560-021-00784-7",
                    "Concept analysis consultata per responsabilità emotive e strumentali, obbligo, equità, riconoscimento e cultura tra giovani caregiver; gli attributi non sono fattori psicometrici."),
            entry("https://doi.org/10.1111/j.1752-0606.2011.00258.x",
                    "Confronto psicometrico di tre misure retrospettive consultato per l'eterogeneità della misurazione; campione statunitense e strumenti diversi non validano l'app."),
            entry("https://doi.org/10.1007/s10826-022-02338-6",
                    "Adattamento polacco del Parentification Inventory consultato per dipendenza culturale e necessità di riverificare struttura e item; non dimostra equivalenza italiana."),
            entry("https://doi.org/10.3389/fpsyt.2022.1079608",
                    "Studio su 605 giovani adulti italiani fratelli di persone con disabilità consultato per distress, supporto e benefici percepiti; campione speciale e disegno correlazionale limitano il trasferimento."),
            entry("https://doi.org/10.1016/j.childyouth.2022.106709",
                    "Revisione integrata consultata per distinguere responsabilità gravose da compiti adeguati, sostenuti e riconosciuti; non fornisce criteri o previsioni individuali."),
            entry("https://doi.org/10.1177/15248380251344316",
                    "Revisione sistematica mixed-methods di 96 record consultata per definizione, tattiche epistemiche, potere ed effetti del gaslighting; l'eterogeneità e il perimetro soprattutto di violenza di genere non validano aree o soglie dell'app."),
            entry("https://doi.org/10.1177/02654075241266942",
                    "Validazione iniziale del GREI in campioni israeliano e statunitense consultata per delimitare l'esposizione riferita in coppia; struttura, item, proprietà e punteggi non vengono trasferiti al questionario originale."),
            entry("https://doi.org/10.1111/pere.12510",
                    "Studio qualitativo su 65 adulti autoselezionati consultato per fiducia epistemica, controllo, contesto ed effetti riferiti; non stima prevalenza, causalità o criteri individuali."),
            entry("https://doi.org/10.1177/0003122419874843",
                    "Analisi sociologica consultata per il ruolo di potere, stereotipi, vulnerabilità e istituzioni nel gaslighting; non è una validazione psicometrica e non dimostra la dinamica nel singolo rapporto."),
            entry("https://doi.org/10.21500/20112084.6306",
                    "Studio su 177 universitari italiani consultato come evidenza locale limitata; la misura dei comportamenti non era formalmente validata in Italia e le associazioni trasversali non spiegano il singolo caso."),
            entry("https://doi.org/10.54119/discovery.zxgc9960",
                    "Primo studio quantitativo specifico consultato per comunicazione intensa nelle fasi iniziali e associazioni esplorative; singolo ateneo, campione giovane e disegno correlazionale non provano intenzione né validano l'app."),
            entry("https://doi.org/10.17336/igusbd.1651349",
                    "Adattamento turco su adulti emergenti consultato per la struttura modificata e l'affidabilità interna modesta; campione non italiano, età ristretta, item e punteggi non sono trasferiti all'app."),
            entry("https://doi.org/10.1007/s10896-025-00970-6",
                    "Revisione sistematica qualitativa consultata per racconti di affetto travolgente nelle fasi iniziali entro il controllo coercitivo; il sottotema compare in pochi studi su donne e non valida il questionario."),
            entry("https://doi.org/10.1016/j.avb.2017.08.003",
                    "Revisione concettuale consultata per distinguere singoli comportamenti dal controllo coercitivo e per i limiti della sua misurazione; non convalida una misura specifica di love bombing."),
            entry("https://www.istat.it/statistiche-per-temi/focus/violenza-sulle-donne/il-contesto/definizioni-e-indicatori/",
                    "Fonte istituzionale italiana consultata per denigrazione, controllo, isolamento e intimidazione nella violenza psicologica; il perimetro riguarda soprattutto donne e partner e non definisce i costrutti specifici dell'app."),
            entry("https://eige.europa.eu/publications-resources/publications/understanding-psychological-violence-against-women-need-harmonised-definitions-and-data-eu",
                    "Sintesi istituzionale europea consultata per il quadro più ampio della violenza psicologica e la necessità di definizioni armonizzate; non è una misura né una valutazione individuale."),
            entry("https://doi.org/10.3390/ijerph17031116",
                    "Studio trasversale spagnolo consultato per la definizione operativa del breadcrumbing e le associazioni con soddisfazione di vita, solitudine e impotenza; non prova causalità e il criterio di frequenza non è un cutoff dell'app."),
            entry("https://doi.org/10.24310/espsiescpsi.v13i2.9960",
                    "Studio su adulti spagnoli consultato per la finestra annuale e il rapporto con l'uso del dating online; prevalenze, metodo e soglie non sono trasferibili agli utenti italiani."),
            entry("https://doi.org/10.3390/ijerph17249548",
                    "Sviluppo di BREAD-ASR consultato per le condotte agite; adolescenti spagnoli, ruolo, struttura, item e punteggi sono diversi e non vengono trasferiti al questionario dell'app."),
            entry("https://doi.org/10.34192/cienciaysalud.v7i3.688",
                    "Costruzione argentina della CEB consultata per esperienza, aspettative ed emozioni riferite; campione locale di giovani adulti e struttura preliminare non validano le aree dell'app."),
            entry("https://doi.org/10.1080/01639625.2025.2516636",
                    "Validazione preliminare spagnola della CEB consultata per la struttura diversa emersa in tre studi; adulti emergenti non italiani e risultati preliminari non autorizzano soglie individuali."),
            entry("https://doi.org/10.3390/soc13020041",
                    "Studio qualitativo consultato per i temi di intermittenza, aspettativa, incongruenza e incertezza; nove giovani adulti, soprattutto studenti e donne, non rappresentano la popolazione generale."),
            entry("https://doi.org/10.1016/j.chb.2025.108637",
                    "Analisi teorica consultata per distinguere breadcrumbing, ghosting e orbiting; non è una validazione psicometrica e non stabilisce il fenomeno nel singolo rapporto."),
            entry("https://www.1522.eu/cose-1522/",
                    "Pagina ufficiale consultata per destinatari, gratuità, disponibilità continuativa e orientamento territoriale del 1522; non è evidenza sul costrutto e non sostituisce il 112 nelle emergenze."),
            entry("https://www.salute.gov.it/new/it/tema/salute-mentale/la-rete-dei-servizi-la-salute-mentale/",
                    "Fonte istituzionale italiana consultata per orientare ai servizi territoriali quando sofferenza o interferenza richiedono una valutazione; non è evidenza sui costrutti dei questionari."));

    public String findByUrl(String url) {
        return CONTRIBUTIONS.getOrDefault(url, DEFAULT_CONTRIBUTION);
    }
}
