spring.application.name=testpsicologici
server.port=${PORT:8080}
spring.datasource.url=${APP_DATABASE_URL:jdbc:h2:file:./data/testpsicologici;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${APP_DATABASE_USERNAME:sa}
spring.datasource.password=${APP_DATABASE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=false
