import Footer from '../components/Footer';
import Navbar from '../components/Navbar';

export default function PrivacyPage({ privacyContactEmail }) {
  return (
    <main className="editorial-shell privacy-shell">
      <Navbar />
      <header className="editorial-hero privacy-hero">
        <p className="eyebrow">Trasparenza</p>
        <h1>Privacy e cookie</h1>
        <p>Spazio Test limita la raccolta ai dati necessari al funzionamento del sito, alle statistiche aggregate e, quando scegli di contribuire, alla gestione del pagamento.</p>
      </header>
      <section className="privacy-content">
        <article><h2>Titolare del trattamento</h2><p>Il titolare del trattamento è Stefano Liga, che gestisce Spazio Test come privato. Puoi contattarlo all'indirizzo indicato in fondo a questa pagina.</p></article>
        <article><h2>Dati dei questionari</h2><p>Le risposte vengono inviate al server e conservate temporaneamente nella sessione del questionario, per consentire la compilazione e calcolare il risultato. Il browser conserva il cookie che permette di ritrovare questa sessione. Le risposte non vengono associate a un account né salvate nel database delle statistiche; restano disponibili fino alla scadenza o all'invalidazione della sessione. Chiudere una scheda non comporta necessariamente la cancellazione immediata della sessione sul server.</p></article>
        <article><h2>Contributi e pagamenti tramite Stripe</h2><p>Se scegli di lasciare un contributo volontario, vieni reindirizzato a una pagina di pagamento ospitata da Stripe. Stripe tratta i dati di contatto, del metodo di pagamento, della transazione e quelli tecnici necessari a elaborare il pagamento, prevenire frodi e gestire eventuali contestazioni secondo la propria <a href="https://stripe.com/privacy">informativa sulla privacy</a>. I dati completi della carta o degli altri metodi di pagamento non transitano nei server di Spazio Test.</p><p>Nel database di Spazio Test vengono registrati soltanto gli identificativi tecnici della sessione e dell'evento Stripe, l'eventuale identificativo del pagamento, l'importo, la valuta, lo stato, la modalità di test o reale e le relative date. Non vengono associati al questionario svolto, alle risposte o al risultato. Le informazioni di contatto e della transazione necessarie alla gestione del pagamento possono restare consultabili nell'account Stripe.</p></article>
        <article><h2>Conteggio giornaliero delle visite</h2><p>Il database delle statistiche conserva esclusivamente, per ogni data, il numero complessivo di browser distinti che hanno caricato almeno una pagina. In questo conteggio non vengono salvati indirizzo IP, User-Agent, pagina visitata, argomento consultato, provenienza o identificatori individuali.</p></article>
        <article><h2>Completamenti dei questionari</h2><p>Quando un questionario viene concluso, viene incrementato il relativo totale giornaliero. Il dato indica soltanto quante volte ogni questionario è stato completato: non viene collegato al browser, alle risposte o al risultato ottenuto e non richiede cookie aggiuntivi.</p></article>
        <article><h2>Pagine non trovate</h2><p>Quando viene richiesto un indirizzo inesistente, viene registrato soltanto il percorso privo della query string e incrementato il relativo conteggio. Questa statistica serve a individuare collegamenti interrotti: non conserva indirizzo IP, User-Agent, provenienza o identificatori del visitatore.</p></article>
        <article><h2>Cookie utilizzati</h2><p><strong>__Host-st_visit_day</strong> è un cookie analytics di prima parte, uguale per tutti i visitatori della stessa giornata. Indica soltanto che il browser è già stato incluso nel conteggio e scade alla mezzanotte nel fuso Europe/Rome. <strong>JSESSIONID</strong> è un cookie tecnico temporaneo usato durante i questionari e per l'accesso riservato alla dashboard.</p></article>
        <article><h2>Finalità e conservazione</h2><p>Le statistiche servono a comprendere il volume d'uso complessivo di Spazio Test e a correggere collegamenti non funzionanti. I conteggi aggregati possono essere conservati nel tempo perché non permettono di ricostruire la navigazione o identificare un visitatore.</p></article>
        <article><h2>Cookie pubblicitari</h2><p>Non vengono utilizzati cookie pubblicitari o di profilazione. Il cookie statistico è gestito direttamente da Spazio Test per produrre statistiche aggregate relative a questo solo sito; per questo non viene richiesto un consenso tramite banner.</p></article>
        <article><h2>Hosting e servizi esterni</h2><p>Il sito è ospitato su Railway, che fornisce l'infrastruttura necessaria al funzionamento dell'applicazione. Le connessioni al sito comportano il trattamento di dati tecnici, come l'indirizzo IP, distinto dal conteggio aggregato delle visite. Per informazioni sul fornitore consulta l'<a href="https://railway.com/legal/privacy">informativa Railway</a>.</p><p>I caratteri tipografici sono caricati tramite Google Fonts: il browser contatta i server Google e trasmette i dati tecnici necessari alla richiesta. Consulta l'<a href="https://policies.google.com/privacy?hl=it">informativa Google</a>. Stripe gestisce i pagamenti volontari descritti sopra. I servizi esterni possono comportare trattamenti fuori dallo Spazio economico europeo; le rispettive informative descrivono il trattamento e le garanzie applicabili.</p></article>
        <article><h2>Richieste e diritti</h2><p>Scrivendo al titolare puoi chiedere, nei casi previsti dal GDPR, accesso ai tuoi dati, rettifica, cancellazione, limitazione, portabilità e opposizione al trattamento. Quando un trattamento si basa sul consenso, puoi revocarlo senza pregiudicare la liceità del trattamento precedente. Puoi inoltre presentare un reclamo al <a href="https://www.garanteprivacy.it/">Garante per la protezione dei dati personali</a>.</p><p>Le richieste inviate via email sono utilizzate per rispondere e gestire la richiesta. Non inviare risposte ai questionari o informazioni sulla salute se non sono necessarie. I conteggi aggregati non consentono di individuare il contributo di un singolo visitatore.</p></article>
        <article><h2>Contatti</h2>{privacyContactEmail
          ? <p>Per richieste relative alla privacy puoi scrivere a <a href={`mailto:${privacyContactEmail}`}>{privacyContactEmail}</a>.</p>
          : <p>Il recapito privacy del titolare non è ancora stato configurato.</p>}</article>
      </section>
      <Footer />
    </main>
  );
}
